language: node_js
node_js:
  - '8.9.3'
services:
  - mongodb

script: babel-istanbul cover node_modules/mocha/bin/_mocha -- --require babel-polyfill -R  spec
before_script:
  - npm install codacy-coverage babel-cli babel-polyfill  babel-preset-env codeclimate-test-reporter babel-istanbul -g
after_script:
  - cat ./coverage/lcov.info | codacy-coverage && codeclimate-test-reporter < ./coverage/lcov.inform && rm -rf ./coverage

